// Shared analysis prompt builder — pure, browser-safe.
import type { ExplanationLanguage } from "./prompt";

export type AnalysisKind =
  | "smells"
  | "deadcode"
  | "bugs"
  | "security"
  | "ai_origin";

const FOCUS: Record<AnalysisKind, string> = {
  smells:
    "Identify code smells: long functions, unclear naming, duplication, deep nesting, tight coupling, leaky abstractions. For each issue provide: location, why it is a smell, and a refactoring suggestion.",
  deadcode:
    "Identify likely dead code: unused variables, unreachable branches, unused exports, unused imports. Be conservative — only report items you can justify from the file alone. Note false-positive risk when context could prove usage elsewhere.",
  bugs:
    "Identify likely bugs: off-by-one errors, missing await, race conditions, null/undefined access, exhaustiveness mistakes, incorrect error handling. Rank by likelihood and impact.",
  security:
    "Identify potential security issues: injection, XSS, SSRF, insecure deserialization, secret leakage, weak crypto, insufficient authorization checks, unsafe input handling. For each finding: severity (low/medium/high), location, exploitation scenario, mitigation.",
  ai_origin:
    "Estimate the probability (0–100) that THIS FILE was generated by an AI coding assistant (Copilot, Cursor, Claude, ChatGPT, Lovable, etc.) rather than handwritten by a person. Consider signals like: overly uniform naming/comments, textbook boilerplate, exhaustive but shallow doc-comments, lack of idiosyncratic shortcuts, absence of TODO/FIXME/debug residue, excessively defensive error handling, suspiciously consistent style across unrelated sections. Counter-signals: project-specific jargon, asymmetric coding style, in-jokes, ad-hoc hacks, inconsistent formatting. Be calibrated — well-written human code often looks 'clean'. Avoid claiming proof: this is heuristic.",
};

export function buildAnalysisPrompt(args: {
  kind: AnalysisKind;
  language: ExplanationLanguage;
  filePath: string;
  fileContent: string;
}): { system: string; user: string } {
  const langName =
    args.language === "it"
      ? "Italian"
      : args.language === "zh"
        ? "Simplified Chinese"
        : "English";

  const isAiOrigin = args.kind === "ai_origin";

  const findingsBlock = isAiOrigin
    ? ""
    : `

AFTER the prose, append a fenced code block with language tag \`findings-json\` containing a JSON array of the concrete locations referenced in your prose. Each item has shape:
{
  "start_line": <integer>,
  "end_line": <integer>,
  "severity": "info" | "low" | "medium" | "high" | "critical",
  "title": "<short label, <=80 chars>",
  "message": "<one-paragraph explanation tying it to the prose above>"
}
Rules:
- Use the SAME line numbers you see in the file source below (1-indexed).
- Include only findings that point to specific lines/ranges. Omit generic remarks.
- Maximum 25 items. Keep it small and high-signal.
- If there are NO findings, output an empty array \`[]\`.
- Do NOT add any commentary inside the fenced block — JSON only.

Example:
\`\`\`findings-json
[
  {"start_line": 42, "end_line": 47, "severity": "high", "title": "Missing await on async call", "message": "fetchUser is async but its promise is dropped, leaving subsequent logic to run on undefined."}
]
\`\`\``;

  const formatRules = isAiOrigin
    ? `OUTPUT FORMAT — STRICT:
Line 1 MUST be exactly: SCORE: <number 0-100>
Line 2 MUST be exactly: VERDICT: <one of human-likely | mixed | ai-likely>
Then a short Markdown body (under ~250 words) with two sections:
- "Signals" — bullets pointing to specific lines/patterns that pushed the score up.
- "Counter-signals" — bullets that pulled it down.
End with one sentence reminding the reader this is a heuristic estimate, not proof.`
    : `If no issues are found, say so plainly — do not invent findings.
Keep the prose under ~500 words.${findingsBlock}`;

  const system = `You are Decoder, performing a focused source-code review.
Reply in ${langName}, using Markdown with clear headings.
${FOCUS[args.kind]}
${formatRules}
Never fabricate code paths you cannot infer from the file.`;

  const content =
    args.fileContent.length > 60_000
      ? args.fileContent.slice(0, 60_000) + "\n…[truncated]"
      : args.fileContent;
  const user = `File: ${args.filePath}\n\n\`\`\`\n${content}\n\`\`\``;
  return { system, user };
}

// Prompt for a per-file unified-diff patch given the prior analysis output.
export function buildFixPrompt(args: {
  language: ExplanationLanguage;
  filePath: string;
  fileContent: string;
  analysisMarkdown: string;
  kindLabel: string;
}): { system: string; user: string } {
  const langName =
    args.language === "it"
      ? "Italian"
      : args.language === "zh"
        ? "Simplified Chinese"
        : "English";

  const system = `You are Decoder, producing a minimal, safe code patch.
Reply in ${langName} for any prose. The patch itself uses standard unified-diff syntax.

OUTPUT FORMAT — STRICT:
1) A single fenced code block tagged \`diff\` containing a VALID unified diff.
   - First two lines per file MUST be: "--- a/<path>" and "+++ b/<path>".
   - Use one or more "@@ -<old>,<count> +<new>,<count> @@" hunk headers.
   - Prefix unchanged context lines with a single space, removed lines with "-", added lines with "+".
   - Keep at least 3 lines of unchanged context around each change when possible.
   - Modify ONLY what is needed to address the issues; do not reformat untouched code.
   - Preserve existing indentation style (tabs vs spaces).
2) After the diff block, a short Markdown section "Notes" (<=120 words) explaining what changed and why, and any manual follow-up required.
If no safe fix is possible, output an empty diff block (\`\`\`diff\n\`\`\`) and explain in Notes.
Never invent symbols, imports, or APIs that are not in the file or its obvious context.`;

  const trimmed =
    args.fileContent.length > 60_000
      ? args.fileContent.slice(0, 60_000) + "\n…[truncated]"
      : args.fileContent;

  const user = `Target file path (use this exact path in the diff headers): ${args.filePath}
Analysis focus: ${args.kindLabel}

=== PRIOR ANALYSIS (resolve these issues) ===
${args.analysisMarkdown.slice(0, 12_000)}

=== CURRENT FILE CONTENT ===
\`\`\`
${trimmed}
\`\`\`
`;
  return { system, user };
}

// Aggregated folder-level report from per-file analyses.
export function buildFolderAggregatePrompt(args: {
  language: ExplanationLanguage;
  kindLabel: string;
  folderPath: string;
  perFile: Array<{ path: string; excerpt: string }>;
}): { system: string; user: string } {
  const langName =
    args.language === "it"
      ? "Italian"
      : args.language === "zh"
        ? "Simplified Chinese"
        : "English";
  const system = `You are Decoder, producing a folder-level synthesis of per-file code reviews.
Reply in ${langName}, using Markdown.
Sections (in order):
1) "## Sintesi" — 3-6 lines summarising the overall health of the folder.
2) "## Pattern ricorrenti" — bullets of issues that repeat across multiple files (cite file names).
3) "## Priorità" — ordered list (most urgent first) with the top 5-8 items to fix and the affected files.
4) "## Per file" — short bullet per file with the headline issue (omit files with no findings).
Do not invent findings. Base everything on the per-file inputs provided.`;

  const items = args.perFile
    .map((p) => `### ${p.path}\n${p.excerpt.slice(0, 4_000)}`)
    .join("\n\n");

  const user = `Folder: ${args.folderPath}
Analysis focus: ${args.kindLabel}
Number of files: ${args.perFile.length}

=== PER-FILE REPORTS ===
${items.slice(0, 50_000)}
`;
  return { system, user };
}
