// Shared analysis prompt builder — pure, browser-safe.
import type { ExplanationLanguage } from "./prompt";

export type AnalysisKind =
  | "smells"
  | "deadcode"
  | "bugs"
  | "security"
  | "ai_origin";

const FOCUS: Record<AnalysisKind, string> = {
  smells:
    "Identify code smells: long functions, unclear naming, duplication, deep nesting, tight coupling, leaky abstractions. For each issue provide: location, why it is a smell, and a refactoring suggestion.",
  deadcode:
    "Identify likely dead code: unused variables, unreachable branches, unused exports, unused imports. Be conservative — only report items you can justify from the file alone. Note false-positive risk when context could prove usage elsewhere.",
  bugs:
    "Identify likely bugs: off-by-one errors, missing await, race conditions, null/undefined access, exhaustiveness mistakes, incorrect error handling. Rank by likelihood and impact.",
  security:
    "Identify potential security issues: injection, XSS, SSRF, insecure deserialization, secret leakage, weak crypto, insufficient authorization checks, unsafe input handling. For each finding: severity (low/medium/high), location, exploitation scenario, mitigation.",
  ai_origin:
    "Estimate the probability (0–100) that THIS FILE was generated by an AI coding assistant (Copilot, Cursor, Claude, ChatGPT, Lovable, etc.) rather than handwritten by a person. Consider signals like: overly uniform naming/comments, textbook boilerplate, exhaustive but shallow doc-comments, lack of idiosyncratic shortcuts, absence of TODO/FIXME/debug residue, excessively defensive error handling, suspiciously consistent style across unrelated sections. Counter-signals: project-specific jargon, asymmetric coding style, in-jokes, ad-hoc hacks, inconsistent formatting. Be calibrated — well-written human code often looks 'clean'. Avoid claiming proof: this is heuristic.",
};

export function buildAnalysisPrompt(args: {
  kind: AnalysisKind;
  language: ExplanationLanguage;
  filePath: string;
  fileContent: string;
}): { system: string; user: string } {
  const langName =
    args.language === "it"
      ? "Italian"
      : args.language === "zh"
        ? "Simplified Chinese"
        : "English";

  const isAiOrigin = args.kind === "ai_origin";

  const formatRules = isAiOrigin
    ? `OUTPUT FORMAT — STRICT:
Line 1 MUST be exactly: SCORE: <number 0-100>
Line 2 MUST be exactly: VERDICT: <one of human-likely | mixed | ai-likely>
Then a short Markdown body (under ~250 words) with two sections:
- "Signals" — bullets pointing to specific lines/patterns that pushed the score up.
- "Counter-signals" — bullets that pulled it down.
End with one sentence reminding the reader this is a heuristic estimate, not proof.`
    : `If no issues are found, say so plainly — do not invent findings.
Keep it under ~500 words.`;

  const system = `You are De-coder, performing a focused source-code review.
Reply in ${langName}, using Markdown with clear headings.
${FOCUS[args.kind]}
${formatRules}
Never fabricate code paths you cannot infer from the file.`;

  const content =
    args.fileContent.length > 60_000
      ? args.fileContent.slice(0, 60_000) + "\n…[truncated]"
      : args.fileContent;
  const user = `File: ${args.filePath}\n\n\`\`\`\n${content}\n\`\`\``;
  return { system, user };
}
