/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DataFlowRouteImport } from './routes/data-flow'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContributorsRouteImport } from './routes/contributors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeConceptsRouteImport } from './routes/knowledge.concepts'
import { Route as KnowledgeCapabilitiesRouteImport } from './routes/knowledge.capabilities'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as DocsStaticCodeAnalysisNoApiKeyRouteImport } from './routes/docs.static-code-analysis-no-api-key'
import { Route as DocsSecureCodeReviewByokRouteImport } from './routes/docs.secure-code-review-byok'
import { Route as DocsPrivacyFirstAiEuropeRouteImport } from './routes/docs.privacy-first-ai-europe'
import { Route as DocsOpenSourceAiCodeReviewRouteImport } from './routes/docs.open-source-ai-code-review'
import { Route as DocsHowToReviewAiCodeRouteImport } from './routes/docs.how-to-review-ai-code'
import { Route as DocsGdprAiCodeReviewRouteImport } from './routes/docs.gdpr-ai-code-review'
import { Route as DocsFreeMalwareScannerSourceCodeRouteImport } from './routes/docs.free-malware-scanner-source-code'
import { Route as DocsEuAiActCodeAnalysisRouteImport } from './routes/docs.eu-ai-act-code-analysis'
import { Route as DocsDetectAiGeneratedCodeRouteImport } from './routes/docs.detect-ai-generated-code'
import { Route as DocsComparisonCoderabbitRouteImport } from './routes/docs.comparison-coderabbit'
import { Route as DocsChatWithYourCodebaseRouteImport } from './routes/docs.chat-with-your-codebase'
import { Route as DocsAiCodeReviewVsHumanRouteImport } from './routes/docs.ai-code-review-vs-human'
import { Route as DocsAiCodeReviewToolsByokRouteImport } from './routes/docs.ai-code-review-tools-byok'
import { Route as DocsAiCodeReviewMilanoNordItaliaRouteImport } from './routes/docs.ai-code-review-milano-nord-italia'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as DocsZhPrivacyFirstAiEuropeRouteImport } from './routes/docs.zh.privacy-first-ai-europe'
import { Route as DocsZhGdprAiCodeReviewRouteImport } from './routes/docs.zh.gdpr-ai-code-review'
import { Route as DocsZhEuAiActCodeAnalysisRouteImport } from './routes/docs.zh.eu-ai-act-code-analysis'
import { Route as DocsItGdprRevisioneCodiceAiRouteImport } from './routes/docs.it.gdpr-revisione-codice-ai'
import { Route as DocsItEuAiActAnalisiCodiceRouteImport } from './routes/docs.it.eu-ai-act-analisi-codice'
import { Route as DocsItAiPrivacyFirstEuropaRouteImport } from './routes/docs.it.ai-privacy-first-europa'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksCleanupStaleRepositoriesRouteImport } from './routes/api/public/hooks/cleanup-stale-repositories'
import { Route as AuthenticatedProjectsProjectIdReposRepoIdRouteImport } from './routes/_authenticated/projects.$projectId.repos.$repoId'
import { Route as AuthenticatedProjectsProjectIdReposRepoIdHistoryRouteImport } from './routes/_authenticated/projects.$projectId.repos.$repoId.history'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFlowRoute = DataFlowRouteImport.update({
  id: '/data-flow',
  path: '/data-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsRoute = ContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeConceptsRoute = KnowledgeConceptsRouteImport.update({
  id: '/knowledge/concepts',
  path: '/knowledge/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCapabilitiesRoute = KnowledgeCapabilitiesRouteImport.update({
  id: '/knowledge/capabilities',
  path: '/knowledge/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsStaticCodeAnalysisNoApiKeyRoute =
  DocsStaticCodeAnalysisNoApiKeyRouteImport.update({
    id: '/static-code-analysis-no-api-key',
    path: '/static-code-analysis-no-api-key',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsSecureCodeReviewByokRoute =
  DocsSecureCodeReviewByokRouteImport.update({
    id: '/secure-code-review-byok',
    path: '/secure-code-review-byok',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPrivacyFirstAiEuropeRoute =
  DocsPrivacyFirstAiEuropeRouteImport.update({
    id: '/privacy-first-ai-europe',
    path: '/privacy-first-ai-europe',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsOpenSourceAiCodeReviewRoute =
  DocsOpenSourceAiCodeReviewRouteImport.update({
    id: '/open-source-ai-code-review',
    path: '/open-source-ai-code-review',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsHowToReviewAiCodeRoute = DocsHowToReviewAiCodeRouteImport.update({
  id: '/how-to-review-ai-code',
  path: '/how-to-review-ai-code',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGdprAiCodeReviewRoute = DocsGdprAiCodeReviewRouteImport.update({
  id: '/gdpr-ai-code-review',
  path: '/gdpr-ai-code-review',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFreeMalwareScannerSourceCodeRoute =
  DocsFreeMalwareScannerSourceCodeRouteImport.update({
    id: '/free-malware-scanner-source-code',
    path: '/free-malware-scanner-source-code',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsEuAiActCodeAnalysisRoute = DocsEuAiActCodeAnalysisRouteImport.update({
  id: '/eu-ai-act-code-analysis',
  path: '/eu-ai-act-code-analysis',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDetectAiGeneratedCodeRoute =
  DocsDetectAiGeneratedCodeRouteImport.update({
    id: '/detect-ai-generated-code',
    path: '/detect-ai-generated-code',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsComparisonCoderabbitRoute =
  DocsComparisonCoderabbitRouteImport.update({
    id: '/comparison-coderabbit',
    path: '/comparison-coderabbit',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsChatWithYourCodebaseRoute =
  DocsChatWithYourCodebaseRouteImport.update({
    id: '/chat-with-your-codebase',
    path: '/chat-with-your-codebase',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsAiCodeReviewVsHumanRoute = DocsAiCodeReviewVsHumanRouteImport.update({
  id: '/ai-code-review-vs-human',
  path: '/ai-code-review-vs-human',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAiCodeReviewToolsByokRoute =
  DocsAiCodeReviewToolsByokRouteImport.update({
    id: '/ai-code-review-tools-byok',
    path: '/ai-code-review-tools-byok',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsAiCodeReviewMilanoNordItaliaRoute =
  DocsAiCodeReviewMilanoNordItaliaRouteImport.update({
    id: '/ai-code-review-milano-nord-italia',
    path: '/ai-code-review-milano-nord-italia',
    getParentRoute: () => DocsRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DocsZhPrivacyFirstAiEuropeRoute =
  DocsZhPrivacyFirstAiEuropeRouteImport.update({
    id: '/zh/privacy-first-ai-europe',
    path: '/zh/privacy-first-ai-europe',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsZhGdprAiCodeReviewRoute = DocsZhGdprAiCodeReviewRouteImport.update({
  id: '/zh/gdpr-ai-code-review',
  path: '/zh/gdpr-ai-code-review',
  getParentRoute: () => DocsRoute,
} as any)
const DocsZhEuAiActCodeAnalysisRoute =
  DocsZhEuAiActCodeAnalysisRouteImport.update({
    id: '/zh/eu-ai-act-code-analysis',
    path: '/zh/eu-ai-act-code-analysis',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsItGdprRevisioneCodiceAiRoute =
  DocsItGdprRevisioneCodiceAiRouteImport.update({
    id: '/it/gdpr-revisione-codice-ai',
    path: '/it/gdpr-revisione-codice-ai',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsItEuAiActAnalisiCodiceRoute =
  DocsItEuAiActAnalisiCodiceRouteImport.update({
    id: '/it/eu-ai-act-analisi-codice',
    path: '/it/eu-ai-act-analisi-codice',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsItAiPrivacyFirstEuropaRoute =
  DocsItAiPrivacyFirstEuropaRouteImport.update({
    id: '/it/ai-privacy-first-europa',
    path: '/it/ai-privacy-first-europa',
    getParentRoute: () => DocsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupStaleRepositoriesRoute =
  ApiPublicHooksCleanupStaleRepositoriesRouteImport.update({
    id: '/api/public/hooks/cleanup-stale-repositories',
    path: '/api/public/hooks/cleanup-stale-repositories',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProjectsProjectIdReposRepoIdRoute =
  AuthenticatedProjectsProjectIdReposRepoIdRouteImport.update({
    id: '/repos/$repoId',
    path: '/repos/$repoId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute =
  AuthenticatedProjectsProjectIdReposRepoIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedProjectsProjectIdReposRepoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/cookies': typeof CookiesRoute
  '/data-flow': typeof DataFlowRoute
  '/docs': typeof DocsRouteWithChildren
  '/install': typeof InstallRoute
  '/manifesto': typeof ManifestoRoute
  '/open-source': typeof OpenSourceRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/docs/ai-code-review-milano-nord-italia': typeof DocsAiCodeReviewMilanoNordItaliaRoute
  '/docs/ai-code-review-tools-byok': typeof DocsAiCodeReviewToolsByokRoute
  '/docs/ai-code-review-vs-human': typeof DocsAiCodeReviewVsHumanRoute
  '/docs/chat-with-your-codebase': typeof DocsChatWithYourCodebaseRoute
  '/docs/comparison-coderabbit': typeof DocsComparisonCoderabbitRoute
  '/docs/detect-ai-generated-code': typeof DocsDetectAiGeneratedCodeRoute
  '/docs/eu-ai-act-code-analysis': typeof DocsEuAiActCodeAnalysisRoute
  '/docs/free-malware-scanner-source-code': typeof DocsFreeMalwareScannerSourceCodeRoute
  '/docs/gdpr-ai-code-review': typeof DocsGdprAiCodeReviewRoute
  '/docs/how-to-review-ai-code': typeof DocsHowToReviewAiCodeRoute
  '/docs/open-source-ai-code-review': typeof DocsOpenSourceAiCodeReviewRoute
  '/docs/privacy-first-ai-europe': typeof DocsPrivacyFirstAiEuropeRoute
  '/docs/secure-code-review-byok': typeof DocsSecureCodeReviewByokRoute
  '/docs/static-code-analysis-no-api-key': typeof DocsStaticCodeAnalysisNoApiKeyRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/capabilities': typeof KnowledgeCapabilitiesRoute
  '/knowledge/concepts': typeof KnowledgeConceptsRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/docs/it/ai-privacy-first-europa': typeof DocsItAiPrivacyFirstEuropaRoute
  '/docs/it/eu-ai-act-analisi-codice': typeof DocsItEuAiActAnalisiCodiceRoute
  '/docs/it/gdpr-revisione-codice-ai': typeof DocsItGdprRevisioneCodiceAiRoute
  '/docs/zh/eu-ai-act-code-analysis': typeof DocsZhEuAiActCodeAnalysisRoute
  '/docs/zh/gdpr-ai-code-review': typeof DocsZhGdprAiCodeReviewRoute
  '/docs/zh/privacy-first-ai-europe': typeof DocsZhPrivacyFirstAiEuropeRoute
  '/api/public/hooks/cleanup-stale-repositories': typeof ApiPublicHooksCleanupStaleRepositoriesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/repos/$repoId': typeof AuthenticatedProjectsProjectIdReposRepoIdRouteWithChildren
  '/projects/$projectId/repos/$repoId/history': typeof AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/cookies': typeof CookiesRoute
  '/data-flow': typeof DataFlowRoute
  '/docs': typeof DocsRouteWithChildren
  '/install': typeof InstallRoute
  '/manifesto': typeof ManifestoRoute
  '/open-source': typeof OpenSourceRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/docs/ai-code-review-milano-nord-italia': typeof DocsAiCodeReviewMilanoNordItaliaRoute
  '/docs/ai-code-review-tools-byok': typeof DocsAiCodeReviewToolsByokRoute
  '/docs/ai-code-review-vs-human': typeof DocsAiCodeReviewVsHumanRoute
  '/docs/chat-with-your-codebase': typeof DocsChatWithYourCodebaseRoute
  '/docs/comparison-coderabbit': typeof DocsComparisonCoderabbitRoute
  '/docs/detect-ai-generated-code': typeof DocsDetectAiGeneratedCodeRoute
  '/docs/eu-ai-act-code-analysis': typeof DocsEuAiActCodeAnalysisRoute
  '/docs/free-malware-scanner-source-code': typeof DocsFreeMalwareScannerSourceCodeRoute
  '/docs/gdpr-ai-code-review': typeof DocsGdprAiCodeReviewRoute
  '/docs/how-to-review-ai-code': typeof DocsHowToReviewAiCodeRoute
  '/docs/open-source-ai-code-review': typeof DocsOpenSourceAiCodeReviewRoute
  '/docs/privacy-first-ai-europe': typeof DocsPrivacyFirstAiEuropeRoute
  '/docs/secure-code-review-byok': typeof DocsSecureCodeReviewByokRoute
  '/docs/static-code-analysis-no-api-key': typeof DocsStaticCodeAnalysisNoApiKeyRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/capabilities': typeof KnowledgeCapabilitiesRoute
  '/knowledge/concepts': typeof KnowledgeConceptsRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/docs/it/ai-privacy-first-europa': typeof DocsItAiPrivacyFirstEuropaRoute
  '/docs/it/eu-ai-act-analisi-codice': typeof DocsItEuAiActAnalisiCodiceRoute
  '/docs/it/gdpr-revisione-codice-ai': typeof DocsItGdprRevisioneCodiceAiRoute
  '/docs/zh/eu-ai-act-code-analysis': typeof DocsZhEuAiActCodeAnalysisRoute
  '/docs/zh/gdpr-ai-code-review': typeof DocsZhGdprAiCodeReviewRoute
  '/docs/zh/privacy-first-ai-europe': typeof DocsZhPrivacyFirstAiEuropeRoute
  '/api/public/hooks/cleanup-stale-repositories': typeof ApiPublicHooksCleanupStaleRepositoriesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/repos/$repoId': typeof AuthenticatedProjectsProjectIdReposRepoIdRouteWithChildren
  '/projects/$projectId/repos/$repoId/history': typeof AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/contributors': typeof ContributorsRoute
  '/cookies': typeof CookiesRoute
  '/data-flow': typeof DataFlowRoute
  '/docs': typeof DocsRouteWithChildren
  '/install': typeof InstallRoute
  '/manifesto': typeof ManifestoRoute
  '/open-source': typeof OpenSourceRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/docs/ai-code-review-milano-nord-italia': typeof DocsAiCodeReviewMilanoNordItaliaRoute
  '/docs/ai-code-review-tools-byok': typeof DocsAiCodeReviewToolsByokRoute
  '/docs/ai-code-review-vs-human': typeof DocsAiCodeReviewVsHumanRoute
  '/docs/chat-with-your-codebase': typeof DocsChatWithYourCodebaseRoute
  '/docs/comparison-coderabbit': typeof DocsComparisonCoderabbitRoute
  '/docs/detect-ai-generated-code': typeof DocsDetectAiGeneratedCodeRoute
  '/docs/eu-ai-act-code-analysis': typeof DocsEuAiActCodeAnalysisRoute
  '/docs/free-malware-scanner-source-code': typeof DocsFreeMalwareScannerSourceCodeRoute
  '/docs/gdpr-ai-code-review': typeof DocsGdprAiCodeReviewRoute
  '/docs/how-to-review-ai-code': typeof DocsHowToReviewAiCodeRoute
  '/docs/open-source-ai-code-review': typeof DocsOpenSourceAiCodeReviewRoute
  '/docs/privacy-first-ai-europe': typeof DocsPrivacyFirstAiEuropeRoute
  '/docs/secure-code-review-byok': typeof DocsSecureCodeReviewByokRoute
  '/docs/static-code-analysis-no-api-key': typeof DocsStaticCodeAnalysisNoApiKeyRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/capabilities': typeof KnowledgeCapabilitiesRoute
  '/knowledge/concepts': typeof KnowledgeConceptsRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/docs/it/ai-privacy-first-europa': typeof DocsItAiPrivacyFirstEuropaRoute
  '/docs/it/eu-ai-act-analisi-codice': typeof DocsItEuAiActAnalisiCodiceRoute
  '/docs/it/gdpr-revisione-codice-ai': typeof DocsItGdprRevisioneCodiceAiRoute
  '/docs/zh/eu-ai-act-code-analysis': typeof DocsZhEuAiActCodeAnalysisRoute
  '/docs/zh/gdpr-ai-code-review': typeof DocsZhGdprAiCodeReviewRoute
  '/docs/zh/privacy-first-ai-europe': typeof DocsZhPrivacyFirstAiEuropeRoute
  '/api/public/hooks/cleanup-stale-repositories': typeof ApiPublicHooksCleanupStaleRepositoriesRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/repos/$repoId': typeof AuthenticatedProjectsProjectIdReposRepoIdRouteWithChildren
  '/_authenticated/projects/$projectId/repos/$repoId/history': typeof AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/contributors'
    | '/cookies'
    | '/data-flow'
    | '/docs'
    | '/install'
    | '/manifesto'
    | '/open-source'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/docs/ai-code-review-milano-nord-italia'
    | '/docs/ai-code-review-tools-byok'
    | '/docs/ai-code-review-vs-human'
    | '/docs/chat-with-your-codebase'
    | '/docs/comparison-coderabbit'
    | '/docs/detect-ai-generated-code'
    | '/docs/eu-ai-act-code-analysis'
    | '/docs/free-malware-scanner-source-code'
    | '/docs/gdpr-ai-code-review'
    | '/docs/how-to-review-ai-code'
    | '/docs/open-source-ai-code-review'
    | '/docs/privacy-first-ai-europe'
    | '/docs/secure-code-review-byok'
    | '/docs/static-code-analysis-no-api-key'
    | '/knowledge/$slug'
    | '/knowledge/capabilities'
    | '/knowledge/concepts'
    | '/knowledge/'
    | '/projects/$projectId'
    | '/docs/it/ai-privacy-first-europa'
    | '/docs/it/eu-ai-act-analisi-codice'
    | '/docs/it/gdpr-revisione-codice-ai'
    | '/docs/zh/eu-ai-act-code-analysis'
    | '/docs/zh/gdpr-ai-code-review'
    | '/docs/zh/privacy-first-ai-europe'
    | '/api/public/hooks/cleanup-stale-repositories'
    | '/lovable/email/queue/process'
    | '/projects/$projectId/'
    | '/projects/$projectId/repos/$repoId'
    | '/projects/$projectId/repos/$repoId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/contributors'
    | '/cookies'
    | '/data-flow'
    | '/docs'
    | '/install'
    | '/manifesto'
    | '/open-source'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/docs/ai-code-review-milano-nord-italia'
    | '/docs/ai-code-review-tools-byok'
    | '/docs/ai-code-review-vs-human'
    | '/docs/chat-with-your-codebase'
    | '/docs/comparison-coderabbit'
    | '/docs/detect-ai-generated-code'
    | '/docs/eu-ai-act-code-analysis'
    | '/docs/free-malware-scanner-source-code'
    | '/docs/gdpr-ai-code-review'
    | '/docs/how-to-review-ai-code'
    | '/docs/open-source-ai-code-review'
    | '/docs/privacy-first-ai-europe'
    | '/docs/secure-code-review-byok'
    | '/docs/static-code-analysis-no-api-key'
    | '/knowledge/$slug'
    | '/knowledge/capabilities'
    | '/knowledge/concepts'
    | '/knowledge'
    | '/docs/it/ai-privacy-first-europa'
    | '/docs/it/eu-ai-act-analisi-codice'
    | '/docs/it/gdpr-revisione-codice-ai'
    | '/docs/zh/eu-ai-act-code-analysis'
    | '/docs/zh/gdpr-ai-code-review'
    | '/docs/zh/privacy-first-ai-europe'
    | '/api/public/hooks/cleanup-stale-repositories'
    | '/lovable/email/queue/process'
    | '/projects/$projectId'
    | '/projects/$projectId/repos/$repoId'
    | '/projects/$projectId/repos/$repoId/history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/contributors'
    | '/cookies'
    | '/data-flow'
    | '/docs'
    | '/install'
    | '/manifesto'
    | '/open-source'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/settings'
    | '/docs/ai-code-review-milano-nord-italia'
    | '/docs/ai-code-review-tools-byok'
    | '/docs/ai-code-review-vs-human'
    | '/docs/chat-with-your-codebase'
    | '/docs/comparison-coderabbit'
    | '/docs/detect-ai-generated-code'
    | '/docs/eu-ai-act-code-analysis'
    | '/docs/free-malware-scanner-source-code'
    | '/docs/gdpr-ai-code-review'
    | '/docs/how-to-review-ai-code'
    | '/docs/open-source-ai-code-review'
    | '/docs/privacy-first-ai-europe'
    | '/docs/secure-code-review-byok'
    | '/docs/static-code-analysis-no-api-key'
    | '/knowledge/$slug'
    | '/knowledge/capabilities'
    | '/knowledge/concepts'
    | '/knowledge/'
    | '/_authenticated/projects/$projectId'
    | '/docs/it/ai-privacy-first-europa'
    | '/docs/it/eu-ai-act-analisi-codice'
    | '/docs/it/gdpr-revisione-codice-ai'
    | '/docs/zh/eu-ai-act-code-analysis'
    | '/docs/zh/gdpr-ai-code-review'
    | '/docs/zh/privacy-first-ai-europe'
    | '/api/public/hooks/cleanup-stale-repositories'
    | '/lovable/email/queue/process'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/repos/$repoId'
    | '/_authenticated/projects/$projectId/repos/$repoId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ContributorsRoute: typeof ContributorsRoute
  CookiesRoute: typeof CookiesRoute
  DataFlowRoute: typeof DataFlowRoute
  DocsRoute: typeof DocsRouteWithChildren
  InstallRoute: typeof InstallRoute
  ManifestoRoute: typeof ManifestoRoute
  OpenSourceRoute: typeof OpenSourceRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeCapabilitiesRoute: typeof KnowledgeCapabilitiesRoute
  KnowledgeConceptsRoute: typeof KnowledgeConceptsRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  ApiPublicHooksCleanupStaleRepositoriesRoute: typeof ApiPublicHooksCleanupStaleRepositoriesRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-flow': {
      id: '/data-flow'
      path: '/data-flow'
      fullPath: '/data-flow'
      preLoaderRoute: typeof DataFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors': {
      id: '/contributors'
      path: '/contributors'
      fullPath: '/contributors'
      preLoaderRoute: typeof ContributorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/concepts': {
      id: '/knowledge/concepts'
      path: '/knowledge/concepts'
      fullPath: '/knowledge/concepts'
      preLoaderRoute: typeof KnowledgeConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/capabilities': {
      id: '/knowledge/capabilities'
      path: '/knowledge/capabilities'
      fullPath: '/knowledge/capabilities'
      preLoaderRoute: typeof KnowledgeCapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/static-code-analysis-no-api-key': {
      id: '/docs/static-code-analysis-no-api-key'
      path: '/static-code-analysis-no-api-key'
      fullPath: '/docs/static-code-analysis-no-api-key'
      preLoaderRoute: typeof DocsStaticCodeAnalysisNoApiKeyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/secure-code-review-byok': {
      id: '/docs/secure-code-review-byok'
      path: '/secure-code-review-byok'
      fullPath: '/docs/secure-code-review-byok'
      preLoaderRoute: typeof DocsSecureCodeReviewByokRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/privacy-first-ai-europe': {
      id: '/docs/privacy-first-ai-europe'
      path: '/privacy-first-ai-europe'
      fullPath: '/docs/privacy-first-ai-europe'
      preLoaderRoute: typeof DocsPrivacyFirstAiEuropeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/open-source-ai-code-review': {
      id: '/docs/open-source-ai-code-review'
      path: '/open-source-ai-code-review'
      fullPath: '/docs/open-source-ai-code-review'
      preLoaderRoute: typeof DocsOpenSourceAiCodeReviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/how-to-review-ai-code': {
      id: '/docs/how-to-review-ai-code'
      path: '/how-to-review-ai-code'
      fullPath: '/docs/how-to-review-ai-code'
      preLoaderRoute: typeof DocsHowToReviewAiCodeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/gdpr-ai-code-review': {
      id: '/docs/gdpr-ai-code-review'
      path: '/gdpr-ai-code-review'
      fullPath: '/docs/gdpr-ai-code-review'
      preLoaderRoute: typeof DocsGdprAiCodeReviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/free-malware-scanner-source-code': {
      id: '/docs/free-malware-scanner-source-code'
      path: '/free-malware-scanner-source-code'
      fullPath: '/docs/free-malware-scanner-source-code'
      preLoaderRoute: typeof DocsFreeMalwareScannerSourceCodeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/eu-ai-act-code-analysis': {
      id: '/docs/eu-ai-act-code-analysis'
      path: '/eu-ai-act-code-analysis'
      fullPath: '/docs/eu-ai-act-code-analysis'
      preLoaderRoute: typeof DocsEuAiActCodeAnalysisRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/detect-ai-generated-code': {
      id: '/docs/detect-ai-generated-code'
      path: '/detect-ai-generated-code'
      fullPath: '/docs/detect-ai-generated-code'
      preLoaderRoute: typeof DocsDetectAiGeneratedCodeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/comparison-coderabbit': {
      id: '/docs/comparison-coderabbit'
      path: '/comparison-coderabbit'
      fullPath: '/docs/comparison-coderabbit'
      preLoaderRoute: typeof DocsComparisonCoderabbitRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/chat-with-your-codebase': {
      id: '/docs/chat-with-your-codebase'
      path: '/chat-with-your-codebase'
      fullPath: '/docs/chat-with-your-codebase'
      preLoaderRoute: typeof DocsChatWithYourCodebaseRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/ai-code-review-vs-human': {
      id: '/docs/ai-code-review-vs-human'
      path: '/ai-code-review-vs-human'
      fullPath: '/docs/ai-code-review-vs-human'
      preLoaderRoute: typeof DocsAiCodeReviewVsHumanRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/ai-code-review-tools-byok': {
      id: '/docs/ai-code-review-tools-byok'
      path: '/ai-code-review-tools-byok'
      fullPath: '/docs/ai-code-review-tools-byok'
      preLoaderRoute: typeof DocsAiCodeReviewToolsByokRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/ai-code-review-milano-nord-italia': {
      id: '/docs/ai-code-review-milano-nord-italia'
      path: '/ai-code-review-milano-nord-italia'
      fullPath: '/docs/ai-code-review-milano-nord-italia'
      preLoaderRoute: typeof DocsAiCodeReviewMilanoNordItaliaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/docs/zh/privacy-first-ai-europe': {
      id: '/docs/zh/privacy-first-ai-europe'
      path: '/zh/privacy-first-ai-europe'
      fullPath: '/docs/zh/privacy-first-ai-europe'
      preLoaderRoute: typeof DocsZhPrivacyFirstAiEuropeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/zh/gdpr-ai-code-review': {
      id: '/docs/zh/gdpr-ai-code-review'
      path: '/zh/gdpr-ai-code-review'
      fullPath: '/docs/zh/gdpr-ai-code-review'
      preLoaderRoute: typeof DocsZhGdprAiCodeReviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/zh/eu-ai-act-code-analysis': {
      id: '/docs/zh/eu-ai-act-code-analysis'
      path: '/zh/eu-ai-act-code-analysis'
      fullPath: '/docs/zh/eu-ai-act-code-analysis'
      preLoaderRoute: typeof DocsZhEuAiActCodeAnalysisRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/it/gdpr-revisione-codice-ai': {
      id: '/docs/it/gdpr-revisione-codice-ai'
      path: '/it/gdpr-revisione-codice-ai'
      fullPath: '/docs/it/gdpr-revisione-codice-ai'
      preLoaderRoute: typeof DocsItGdprRevisioneCodiceAiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/it/eu-ai-act-analisi-codice': {
      id: '/docs/it/eu-ai-act-analisi-codice'
      path: '/it/eu-ai-act-analisi-codice'
      fullPath: '/docs/it/eu-ai-act-analisi-codice'
      preLoaderRoute: typeof DocsItEuAiActAnalisiCodiceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/it/ai-privacy-first-europa': {
      id: '/docs/it/ai-privacy-first-europa'
      path: '/it/ai-privacy-first-europa'
      fullPath: '/docs/it/ai-privacy-first-europa'
      preLoaderRoute: typeof DocsItAiPrivacyFirstEuropaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-stale-repositories': {
      id: '/api/public/hooks/cleanup-stale-repositories'
      path: '/api/public/hooks/cleanup-stale-repositories'
      fullPath: '/api/public/hooks/cleanup-stale-repositories'
      preLoaderRoute: typeof ApiPublicHooksCleanupStaleRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId/repos/$repoId': {
      id: '/_authenticated/projects/$projectId/repos/$repoId'
      path: '/repos/$repoId'
      fullPath: '/projects/$projectId/repos/$repoId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdReposRepoIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/repos/$repoId/history': {
      id: '/_authenticated/projects/$projectId/repos/$repoId/history'
      path: '/history'
      fullPath: '/projects/$projectId/repos/$repoId/history'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdReposRepoIdHistoryRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdReposRepoIdRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdReposRepoIdRouteChildren {
  AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute: typeof AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute
}

const AuthenticatedProjectsProjectIdReposRepoIdRouteChildren: AuthenticatedProjectsProjectIdReposRepoIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute:
      AuthenticatedProjectsProjectIdReposRepoIdHistoryRoute,
  }

const AuthenticatedProjectsProjectIdReposRepoIdRouteWithChildren =
  AuthenticatedProjectsProjectIdReposRepoIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdReposRepoIdRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdReposRepoIdRoute: typeof AuthenticatedProjectsProjectIdReposRepoIdRouteWithChildren
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdReposRepoIdRoute:
      AuthenticatedProjectsProjectIdReposRepoIdRouteWithChildren,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocsRouteChildren {
  DocsAiCodeReviewMilanoNordItaliaRoute: typeof DocsAiCodeReviewMilanoNordItaliaRoute
  DocsAiCodeReviewToolsByokRoute: typeof DocsAiCodeReviewToolsByokRoute
  DocsAiCodeReviewVsHumanRoute: typeof DocsAiCodeReviewVsHumanRoute
  DocsChatWithYourCodebaseRoute: typeof DocsChatWithYourCodebaseRoute
  DocsComparisonCoderabbitRoute: typeof DocsComparisonCoderabbitRoute
  DocsDetectAiGeneratedCodeRoute: typeof DocsDetectAiGeneratedCodeRoute
  DocsEuAiActCodeAnalysisRoute: typeof DocsEuAiActCodeAnalysisRoute
  DocsFreeMalwareScannerSourceCodeRoute: typeof DocsFreeMalwareScannerSourceCodeRoute
  DocsGdprAiCodeReviewRoute: typeof DocsGdprAiCodeReviewRoute
  DocsHowToReviewAiCodeRoute: typeof DocsHowToReviewAiCodeRoute
  DocsOpenSourceAiCodeReviewRoute: typeof DocsOpenSourceAiCodeReviewRoute
  DocsPrivacyFirstAiEuropeRoute: typeof DocsPrivacyFirstAiEuropeRoute
  DocsSecureCodeReviewByokRoute: typeof DocsSecureCodeReviewByokRoute
  DocsStaticCodeAnalysisNoApiKeyRoute: typeof DocsStaticCodeAnalysisNoApiKeyRoute
  DocsItAiPrivacyFirstEuropaRoute: typeof DocsItAiPrivacyFirstEuropaRoute
  DocsItEuAiActAnalisiCodiceRoute: typeof DocsItEuAiActAnalisiCodiceRoute
  DocsItGdprRevisioneCodiceAiRoute: typeof DocsItGdprRevisioneCodiceAiRoute
  DocsZhEuAiActCodeAnalysisRoute: typeof DocsZhEuAiActCodeAnalysisRoute
  DocsZhGdprAiCodeReviewRoute: typeof DocsZhGdprAiCodeReviewRoute
  DocsZhPrivacyFirstAiEuropeRoute: typeof DocsZhPrivacyFirstAiEuropeRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAiCodeReviewMilanoNordItaliaRoute: DocsAiCodeReviewMilanoNordItaliaRoute,
  DocsAiCodeReviewToolsByokRoute: DocsAiCodeReviewToolsByokRoute,
  DocsAiCodeReviewVsHumanRoute: DocsAiCodeReviewVsHumanRoute,
  DocsChatWithYourCodebaseRoute: DocsChatWithYourCodebaseRoute,
  DocsComparisonCoderabbitRoute: DocsComparisonCoderabbitRoute,
  DocsDetectAiGeneratedCodeRoute: DocsDetectAiGeneratedCodeRoute,
  DocsEuAiActCodeAnalysisRoute: DocsEuAiActCodeAnalysisRoute,
  DocsFreeMalwareScannerSourceCodeRoute: DocsFreeMalwareScannerSourceCodeRoute,
  DocsGdprAiCodeReviewRoute: DocsGdprAiCodeReviewRoute,
  DocsHowToReviewAiCodeRoute: DocsHowToReviewAiCodeRoute,
  DocsOpenSourceAiCodeReviewRoute: DocsOpenSourceAiCodeReviewRoute,
  DocsPrivacyFirstAiEuropeRoute: DocsPrivacyFirstAiEuropeRoute,
  DocsSecureCodeReviewByokRoute: DocsSecureCodeReviewByokRoute,
  DocsStaticCodeAnalysisNoApiKeyRoute: DocsStaticCodeAnalysisNoApiKeyRoute,
  DocsItAiPrivacyFirstEuropaRoute: DocsItAiPrivacyFirstEuropaRoute,
  DocsItEuAiActAnalisiCodiceRoute: DocsItEuAiActAnalisiCodiceRoute,
  DocsItGdprRevisioneCodiceAiRoute: DocsItGdprRevisioneCodiceAiRoute,
  DocsZhEuAiActCodeAnalysisRoute: DocsZhEuAiActCodeAnalysisRoute,
  DocsZhGdprAiCodeReviewRoute: DocsZhGdprAiCodeReviewRoute,
  DocsZhPrivacyFirstAiEuropeRoute: DocsZhPrivacyFirstAiEuropeRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ContributorsRoute: ContributorsRoute,
  CookiesRoute: CookiesRoute,
  DataFlowRoute: DataFlowRoute,
  DocsRoute: DocsRouteWithChildren,
  InstallRoute: InstallRoute,
  ManifestoRoute: ManifestoRoute,
  OpenSourceRoute: OpenSourceRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeCapabilitiesRoute: KnowledgeCapabilitiesRoute,
  KnowledgeConceptsRoute: KnowledgeConceptsRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  ApiPublicHooksCleanupStaleRepositoriesRoute:
    ApiPublicHooksCleanupStaleRepositoriesRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
